baseURL = "https://www.example.org/"
languageCode = "zh-cn"
theme = "aafu"

[params]
    title = "KW的主页"
    author = "Kin Wang"
    description = "KW的个人网站"
    copyright = "Kin Wang"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = false
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Kin Wang"
        tagline = "写不完的作业"
        location = "天王星"
        photo = "IMG_7377.JPG"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "http://linkedin.com/kkww"  #这个地方写你的LinkedIn地址
            title = "LinkedIn"		
        #[[params.social.list]]      #我不想要这个部分，所以我前面都加了“#”
        #    class = "fab"
        #    icon = "fa-stack-overflow"
        #    url = "#"
        #    title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
	            #[[params.social.list]]    #不想要这个
        #        class = "ai"
        #        icon = "ai-google-scholar"
        #        url = "#"
        #        title = "Google Scholar"
	             [[params.social.list]]     #改成知乎
            class = "fab"    #把ai改成fab
            icon = "fa-zhihu"   #改成fa-zhihu
            url = "#"        #你的知乎地址
            title = "Zhihu"   #改成Zhihu

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    #[[params.showInAccordion]]    #不想要
    #    item = "hobby"

    [params.aboutme]
      title = "关于我"
      icon = "fas fa-user"
      description = "就一逗比青年，没啥可介绍的"  #你想些啥写啥
  # Experience section
  [params.experience]
      title = "工作经验"
      icon = "fas fa-briefcase"

      [[params.experience.list]]
          position = "做梦师"   #你的职位
          dates = "2019 - *Present*"    #时间
          company = "做梦工厂"   #公司
          details = "负责个人做梦，同时也负责让别人做梦"  #工作内容
      [[params.experience.list]]
          position = "咸鱼"
          dates = "2018 - 2019"
          link = "#"    #你公司的网页地址，你要是不想，可以删掉
          company = "阿里wawa"   #公司名
          #你要是想加个details，就复制上面那个
          details = "尽一切努力不做拼夕夕人！"

  # Education section
  [params.education]
      title = "教育经历"
      icon = "fas fa-graduation-cap"

      [[params.education.list]]
          degree = "做梦学博士"    #你的学位
          college = "做梦大学"   #学校
          dates = "2013 - 2018"   #时间
          #thesis_title = "Effect of humans on other humans: a study of human behavior."
          #thesis_link = "#"
      [[params.education.list]]
          degree = "咸鱼学硕士"
          college = "咸鱼大学"
          dates = "2013 - 2018"
          #thesis_title = "Effect of humans on other humans: a study of human behavior."
          #thesis_link = "#"
      [[params.education.list]]
          degree = "不知道学了啥的学士"
          college = "不知道大学"
          dates = "2004 - 2009"
       #写这个代码的人真无聊，毕业论文题目和链接都给
  # Publication section
  [params.publication]
      title = "发表情况"   #发表文章情况
      icon = "fas fa-book"
      #The order below determines the order in which the items appear in "Publications" section
      format = ["date", "authors", "title", "journal"]
      #If you don't want to group publications, comment the line below by adding # at the beginning
      types = ["期刊文章", "会议"]

      [[params.publication.list]]
          title = "写到这才发现，这个主题的coder写的不是英文"   #文章名
          authors = "K Wang, Y Wang"     #作者
          date = "2018"    #日期
          journal = "Journal of Field 52 (16), 9033-9044"    #期刊
          link = "#"      #链接
          type = "期刊文章"     #文章类型

      #[[params.publication.list]]
      #    title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
      #    authors = "F Last, F Second, P secondary"
      #    date = "2018"
      #    journal = "Journal of Field 52 (16), 9033-9044"
      #    link = "#"
      #    type = "Journal Articles"
	
      [[params.publication.list]]
          title = "论如何做梦"
          authors = "K Wang"
          date = "2018"
          journal = "世界做梦大会"
          link = "#"
          type = "会议"

  # Project section
  [params.project]
      title = "项目"     #项目
      icon = "fas fa-project-diagram"

      [[params.project.list]]
          title = "做梦一天"   #项目名称
          url = "#"     #链接
          description = "就做梦一天呗"    #描述
      [[params.project.list]]
          title = "做梦一周"     #项目
          url = "#"
          description = "就做梦一周啊"
      [[params.project.list]]
          title = "做梦一个月"
          url = "#"
          description = "就一个月都做梦哎"
      [[params.project.list]]
          title = "一直做梦"
          url = "#"
          description = "活到老，梦到老"            

  # Skill section
  [params.skill]
      title = "技能"
      panelId = "skill-panel"
      icon = "fas fa-cogs"

      [[params.skill.list]]
          skill = "好吃懒做, 做梦"     #名称
          skillrating = 90             #评级
      [[params.skill.list]]
          skill = "咸鱼"
          skillrating = 80
      [[params.skill.list]]
          skill = "吃"
          skillrating = 50

  #Hobby section
  #[params.hobby]
     #title = "Hobbies"
     #icon = "fas fa-gamepad"
  	
     #[[params.hobby.list]]		
	        #hobby = "Cooking"
     #[[params.hobby.list]]		
	        #hobby = "Hiking"
     #[[params.hobby.list]]		
	        #hobby = "Baking"